services:
  database:
    image: postgres:15.2
    container_name: database_container
    environment:
      POSTGRES_USER: admon
      POSTGRES_PASSWORD: acuario248
      POSTGRES_DB: postgress
    volumes:
      - userapidata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - user_api_network
  
  restapi:
    image: usuariosapi
    container_name: rest_api_container
    depends_on:
      - database
    environment:
      - DB_HOST=database_container
      - DB_PORT=5432
      - DB_USER=admon
      - DB_PASSWORD=acuario248
      - DB_database=Usuarios
      - LOGS_LOCATION=/home/jboss/logs/app.log
    ports:
      - "8080:8080"
    networks:
      - user_api_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  user_api_network:
    driver: bridge

volumes:
  userapidata:
    external: true