services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: mysqlDB
      MYSQL_USER: admon
      MYSQL_PASSWORD: acuario248
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-ptoor"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  rest:
    image: mtzangel/my-rest-app:1.0.0-SNAPSHOT
    container_name: rest_container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql_container
      DB_PORT: 3306
      DB_NAME: mysqlDB
      DB_USER: root
      DB_PASSWORD: toor
    ports:
      - "8080:8080"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge