version: '3.8'
services:
  database:
    image: postgres:15.2
    container_name: database_container
    environment:
      POSTGRES_USER: admon
      POSTGRES_PASSWORD: acuario248
      POSTGRES_DB: postgress
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - user_api_network
  
  restapi:
    image: usuariosapi
    container_name: rest_api_container
    depends_on:
      - database
    environment:
      - DB_HOST=database_container
      - DB_PORT=5432
      - DB_USER=admon
      - DB_PASSWORD=acuario248
      - DB_database=Usuarios
    ports:
      - "8080:8080"
    networks:
      - user_api_network

networks:
  user_api_network:
    driver: bridge